# Generated by Django 4.2 on 2023-04-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('ID_Permiso', models.BigAutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('ID_Rol', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=15)),
                ('Otros_atributos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=180)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ID_Usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=15)),
                ('Apellidos', models.CharField(max_length=15)),
                ('Contrasena', models.CharField(max_length=20)),
            ],
        ),
    ]
