# Generated by Django 4.2 on 2023-04-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
