# Generated by Django 4.2 on 2023-04-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_todo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relacion_Usuario_Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Rol', models.ManyToManyField(to='todo_api.rol')),
                ('ID_Usuario', models.ManyToManyField(to='todo_api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Relacion_Rol_Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Permiso', models.ManyToManyField(to='todo_api.permiso')),
                ('ID_Rol', models.ManyToManyField(to='todo_api.rol')),
            ],
        ),
    ]
