# Generated by Django 4.2 on 2023-04-11 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0003_relacion_usuario_rol_relacion_rol_permiso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
